### PR TITLE
ZMana

### PR DESCRIPTION
**Pull request by jstruzik**

### CODE REVIEW

**Comment by jstruzik** [comment]
giff me :+1:

**Comment by sicktestuser** [comment]
no, giff :+1:

**Comment by sicktestuser** [comment]
give 2 :+1:

**Comment by sicktestuser** [comment]
give :+1: :-1:

**Comment by sicktestuser** [comment]
give new commit :+1:

**Comment by sicktestuser** [comment]
give new commmit :+1: again

**Pull request closed without merging**
